plugins {
    id 'com.android.application'
}

android {
    namespace 'com.systutor.g4probe'
    compileSdk 34
    buildToolsVersion '34.0.0'

    defaultConfig {
        applicationId 'com.systutor.g4probe'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1'
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
